name: cft
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  auto_route: ^8.3.0
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator:
  build_runner:

flutter:
  uses-material-design: true
